name: CI - Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: #permite ejecutar manualmente el workflow

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16,18]

    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v3
          
      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache de dependencias
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Compilar proyecto
        run: npm run build
      
      - name: Listar archivos finales
        run: ls -la

      - name: Construir Docker imagen
        run: |
          docker build -t mi-proyecto:latest .
      
      - name: Levantar container para prueba
        run: |
          docker run -d -p 3000:3000 --name test-container mi-proyecto:latest
          sleep 5
          curl -f http://localhost:3000/ || (echo "Error: la app no responder" && exit 1)
          docker stop test-container
          docker rm test-container